imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator: { fallbacks: [fr] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Mooc\UserBundle\Entity\User
    registration:
        confirmation:
            enabled: true

hwi_oauth:
    http_client:
        verify_peer: false
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    connect:
        account_connector: app.provider.oauth
    resource_owners:
        facebook:
            type:                facebook
            client_id:           1722477904656254
            client_secret:       6f376de3f89cd54ad1b9808afeebe4b7
            scope:               "email, public_profile"
            infos_url:           "https://graph.facebook.com/me?fields=id,name,email,picture.type(square)"
            paths:
                email: email
            options:
                display: page
        google:
            type:                google
            client_id:           1045127214815-jahctk38vvo76hh1ujls4jou0o1839o9.apps.googleusercontent.com
            client_secret:       AIzaSyAXVbTqOxVLz-JdQ_uRYOb8sMG-bC-Vrao
            scope:              "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            paths:
                email: email
    

# app/config/config.yml
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
            contexts:   [admin]
        sonata.block.service.rss:
            contexts:   [admin]
        sonata.admin.block.stats:
            contexts:   [admin]
        sonata.timeline.block.timeline:
            contexts:   [admin]
        sonata.news.block.recent_posts:
            contexts:   [admin]
        sonata.news.block.recent_comments:
            contexts:   [admin]
        
        
sonata_admin:
    title: Mooc Admin
    title_logo: bundles/sonataadmin/small_logo.png
    dashboard:
        groups:
            admin.users:
                label: Users
                label_catalogue: PiBundle
                items:
                    - admin.users
                    
            admin.courses:
                label: Courses
                label_catalogue: PiBundle
                items:
                    
                    - admin.courses
            
        blocks:
            -
                position: top
                class: col-md-6
                
                type: sonata.admin.block.admin_list
                
            -
                position: right
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Welcome to the Sonata Admin</h2>
                        <p>This is a <code>sonata.block.service.text</code> from the Block
                        Bundle, you can create and add new block in these area by configuring
                        the <code>sonata_admin</code> section.</p> <br /> For instance, here
                        a RSS feed parser (<code>sonata.block.service.rss</code>):
            -
                position: right
                type: sonata.block.service.rss
                
                settings:
                    title: Sonata Project's Feeds
                    url: https://sonata-project.org/blog/archive.rss
 


nomaya_social:
    buttons:
        facebook:
            url:            "https://web.facebook.com/MoocEsprit/"
            locale:         "fr_FR"
            send:           false
            width:          300
            showFaces:      false
            layout:         "button_count"
        twitter:
            url:            "https://twitter.com/moocesprit"
            locale:         "fr"
            message:        "Je veux partager ça avec vous"
            text:           "Tweet"
            via:            "L'Equipe cartedevisitevirtuelle.fr"
            tag:            "ttot"
        googleplus:
            url:            null
            locale :        "fr"
            size :          "medium"
            annotation :    "bubble"
            width :         300
        linkedin:            
            url:            null
            locale:         "fr_FR"
            counter:        "right"
        pinterest:
            url:            null
    links: 
        facebook:           "http://www.facebook.com/yann.chauvel"
        googleplus:         "https://plus.google.com/105931415830389032796"
    theme:                  'default' # optional

#pagination configuration

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    encryption: ssl
    auth_mode: login
    port: 465
    host:      smtp.gmail.com
    username:  3azouz3atef@gmail.com
    password:  titeufazz
    spool:     { type: memory }

services:
    fos_user.doctrine_registry:
        alias: doctrine