mooc_user:
    resource: "@MoocUserBundle/Resources/config/routing.yml"
    prefix:   /

mooc_profil:
    resource: "@MoocProfilBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
 
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
    
pidev_mail:
    resource: "@MoocMailBundle/Resources/config/routing.yml"
    prefix:   /

pidev_mooc:
    resource: "@MoocMoocBundle/Resources/config/routing.yml"
    prefix:   /home


admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
pi:
    resource: "@PiBundle/Resources/config/routing.yml"
    prefix:   /admin
    
mooc_quizz:
    resource: "@MoocQuizzBundle/Resources/config/routing.yml"
    prefix:   /quizz
    
mooc_course:
    resource: "@MoocCourseBundle/Resources/config/routing.yml"
    prefix:   /
    