<?php

namespace Mooc\QuizzBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuizzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizzRepository extends EntityRepository {

    public function getQuizzId() {
        $query = $this->getEntityManager()
                ->createQuery('select max(q.id_quizz) from MoocQuizzBundle:Quizz q ');
       
        return $query->getResult();
}
}