<?php

namespace Mooc\MoocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoursesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursesRepository extends EntityRepository
{
public function findCourseDQL($courseTitle){
    $query=$this->getEntityManager()
            ->createQuery("SELECT v from MoocMoocBundle:Courses v WHERE v.courseTitle like :n  ")
            ->setParameter('n','%'.$courseTitle.'%');
    return $query->getResult();
}
    
}
