<?php

namespace Mooc\MoocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VideoConferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoConferenceRepository extends EntityRepository
{

public function findVideoDQL($course){
    $query=$this->getEntityManager()
            ->createQuery("SELECT v from MoocMoocBundle:VideoConference v WHERE v.course like :n  ")
            ->setParameter('n','%'.$course.'%');
    return $query->getResult();
}

public function selectVideoDQL(){
    $query=$this->getEntityManager()
            ->createQuery("SELECT v from MoocMoocBundle:VideoConference v ")
           ->setMaxResults(3);
    return $query->getResult();
}
}
    


